/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    events: Event;
    videos: Video;
    research: Research;
    team: Team;
    partners: Partner;
    persons: Person;
    'taiji-sources': TaijiSource;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    persons: PersonsSelect<false> | PersonsSelect<true>;
    'taiji-sources': TaijiSourcesSelect<false> | TaijiSourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'about-block': AboutBlock;
    'society-page': SocietyPage;
    'contacts-page': ContactsPage;
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'about-block': AboutBlockSelect<false> | AboutBlockSelect<true>;
    'society-page': SocietyPageSelect<false> | SocietyPageSelect<true>;
    'contacts-page': ContactsPageSelect<false> | ContactsPageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Лента /news и страницы отдельных материалов.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Полный заголовок — h1 статьи и заголовок карточки в ленте.
   */
  title: string;
  /**
   * Для хлебных крошек. Если пусто — возьмётся полный.
   */
  shortTitle?: string | null;
  /**
   * Показывается в ленте и в описании при репосте. 1–3 предложения.
   */
  excerpt: string;
  /**
   * Шапка статьи и обложка карточки. Без фото блок просто не выводится.
   */
  image?: (number | null) | Media;
  /**
   * Необязательно — по умолчанию берётся из карточки файла.
   */
  imageAlt?: string | null;
  body?:
    | (
        | {
            text: string;
            lead?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            image: number | Media;
            /**
             * Если пусто — возьмётся из карточки файла.
             */
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            /**
             * Вида https://rutube.ru/play/embed/<код>
             */
            embed: string;
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Вставляется в статью как есть — виджеты, таблицы, карты, iframe. Код никак не проверяется: ошибка в разметке может поехать по вёрстке страницы. Вставки со <script> оживают только после полной перезагрузки страницы.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'html';
          }
      )[]
    | null;
  author?: {
    name?: string | null;
    role?: string | null;
  };
  date: string;
  /**
   * Латиницей. Оставьте пустым — соберётся из заголовка.
   */
  slug?: string | null;
  /**
   * Оставьте пустым — посчитается по объёму текста.
   */
  readingTime?: string | null;
  /**
   * Такие материалы собираются в хабе конференции на странице «Исследования».
   */
  isConference?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Фотографии новостей, портреты, логотипы и иллюстрации.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Что изображено — читают скринридеры и поисковики. Например: «Участники конференции в зале ИКСА РАН».
   */
  alt: string;
  /**
   * Необязательно. Показывается под фотографией.
   */
  caption?: string | null;
  /**
   * Для фотографий с обязательной атрибуцией (CC-BY и подобные).
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Предстоящие и прошедшие события Общества.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  desc: string;
  place?: string | null;
  image?: (number | null) | Media;
  /**
   * Регистрация или страница события. Необязательно.
   */
  url?: string | null;
  date: string;
  status: 'upcoming' | 'past';
  updatedAt: string;
  createdAt: string;
}
/**
 * Вкладка «Видео» на странице «Медиа-архив».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * В карточке видно первый абзац, в выезжающей панели — все.
   */
  desc?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  embeds?:
    | {
        /**
         * Вида https://rutube.ru/play/embed/<код>
         */
        src: string;
        /**
         * Нужна, только если роликов несколько: «Часть 1» и так далее.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  date: string;
  /**
   * Латиницей. Оставьте пустым — соберётся из заголовка.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Блоки «Источники» и «Публикации» на странице /research.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: number;
  title: string;
  /**
   * О чём материал — 1–2 предложения.
   */
  desc: string;
  /**
   * Открывается в новой вкладке.
   */
  url: string;
  /**
   * Обычно домен источника: например shiyanbin.ru
   */
  label: string;
  kind: 'source' | 'publication';
  /**
   * У классических трактатов года нет — оставьте пустым.
   */
  year?: string | null;
  /**
   * Меньше — выше в списке.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Порядок карточек задаётся полем «Порядок».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  portrait?: (number | null) | Media;
  /**
   * Короткое вступление перед биографией.
   */
  description?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  history?:
    | {
        text: string;
        /**
         * Нужен редко — например для перечисления текущих должностей.
         */
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Меньше — выше. Председатели идут первыми.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  /**
   * Меньше — выше в списке.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * Выводится с пометкой языка — для корректного чтения скринридерами.
   */
  cjk?: string | null;
  /**
   * Надзаголовок карточки: например «Стиль Чэнь».
   */
  line: string;
  /**
   * Пара предложений — что показать в сетке персоналий.
   */
  card: string;
  /**
   * Только изображения в общественном достоянии или под свободной лицензией.
   */
  portrait?: (number | null) | Media;
  /**
   * Пары «ярлык — значение»: линия, годы жизни, ключевое значение.
   */
  meta?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  bio?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Показываются в панели «Подробнее» этой персоналии.
   */
  sources?: (number | TaijiSource)[] | null;
  /**
   * Меньше — выше в сетке.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Показываются внутри панели «Подробнее» у каждой персоналии.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taiji-sources".
 */
export interface TaijiSource {
  id: number;
  /**
   * Сквозная нумерация сносок.
   */
  n: number;
  title: string;
  desc: string;
  /**
   * Если источник только печатный — оставьте пустым.
   */
  url?: string | null;
  /**
   * Обычно домен: например unesco.org
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Как называется документ на сайте.
   */
  title: string;
  /**
   * Строка под названием: например «Принят на учредительном собрании 04.03.2024 г.»
   */
  subtitle?: string | null;
  /**
   * Меньше — выше в списке.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Показывается в правом верхнем углу админки.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'research';
        value: number | Research;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'persons';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'taiji-sources';
        value: number | TaijiSource;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  shortTitle?: T;
  excerpt?: T;
  image?: T;
  imageAlt?: T;
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              lead?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              embed?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        html?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
      };
  author?:
    | T
    | {
        name?: T;
        role?: T;
      };
  date?: T;
  slug?: T;
  readingTime?: T;
  isConference?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  desc?: T;
  place?: T;
  image?: T;
  url?: T;
  date?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  desc?:
    | T
    | {
        text?: T;
        id?: T;
      };
  embeds?:
    | T
    | {
        src?: T;
        label?: T;
        id?: T;
      };
  date?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T;
  desc?: T;
  url?: T;
  label?: T;
  kind?: T;
  year?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  portrait?: T;
  description?:
    | T
    | {
        text?: T;
        id?: T;
      };
  history?:
    | T
    | {
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons_select".
 */
export interface PersonsSelect<T extends boolean = true> {
  name?: T;
  cjk?: T;
  line?: T;
  card?: T;
  portrait?: T;
  meta?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  bio?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sources?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taiji-sources_select".
 */
export interface TaijiSourcesSelect<T extends boolean = true> {
  n?: T;
  title?: T;
  desc?: T;
  url?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Первый экран: карточки «Общество» и «Тайцзицюань».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Ровно две — так собран макет первого экрана.
   */
  cards?:
    | {
        title: string;
        description: string;
        /**
         * Внутренний адрес, например /society
         */
        href: string;
        /**
         * Пропорция 2:1 — иначе кроп съест края.
         */
        image: number | Media;
        /**
         * Если пусто — возьмётся из карточки файла.
         */
        imageAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Сетка 2×2 на главной, ведёт в разделы /taijiquan/*.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-block".
 */
export interface AboutBlock {
  id: number;
  heading: string;
  subtitle?: string | null;
  cards?:
    | {
        title: string;
        desc: string;
        href: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Миссия и ценности. Состав команды и партнёров — в отдельных разделах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "society-page".
 */
export interface SocietyPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  missionHeading?: string | null;
  missionParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * На десктопе — сетка, на мобильных — слайдер.
   */
  values?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Телефон, почта и карта берутся из «Настроек сайта».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page".
 */
export interface ContactsPage {
  id: number;
  heading?: string | null;
  intro?: string | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Меню, подвал и верхняя строка ссылок.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  columns?:
    | {
        title: string;
        href: string;
        links?:
          | {
              label: string;
              /**
               * Можно якорь: /society#team
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Отдельный блок в меню и подвале.
   */
  bigLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Горизонтальная строка на десктопе. Подсветка активного пункта — по адресу.
   */
  topNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контакты и подписи, которые повторяются на всех страницах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone: string;
  /**
   * В формате +79037479367 — подставляется в tel:
   */
  phoneHref: string;
  email: string;
  address?: string | null;
  workingHours?: string | null;
  supportLine1?: string | null;
  supportLine2?: string | null;
  /**
   * Порядок здесь = порядок кнопок в меню и подвале.
   */
  socials?:
    | {
        /**
         * Определяет, какая иконка подставится.
         */
        network: 'messenger' | 'telegram' | 'whatsapp' | 'vk';
        alt: string;
        /**
         * Пока ссылки нет — поставьте #
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ссылка на встраивание конструктора карт — показывается на странице контактов.
   */
  mapEmbed?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        image?: T;
        imageAlt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-block_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  cards?:
    | T
    | {
        title?: T;
        desc?: T;
        href?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "society-page_select".
 */
export interface SocietyPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  missionHeading?: T;
  missionParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page_select".
 */
export interface ContactsPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  ctaTitle?: T;
  ctaText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        href?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  bigLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  topNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  phoneHref?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  supportLine1?: T;
  supportLine2?: T;
  socials?:
    | T
    | {
        network?: T;
        alt?: T;
        href?: T;
        id?: T;
      };
  mapEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}